import Head from "next/head";
import styles from "../styles/connect_wallet_button.module.css";
import React, { useEffect } from "react";

// declare global {
//     interface Window {
//         ethereum:any;
//     }
// }
// let ethereum = window.ethereum;

export function CreateConnectWalletButton() {
    useEffect(() => {
        // Web3 Browswer Detection
        if (typeof (window as any).ethereum !== "undefined") {
            console.log("Injected Web3 Wallet is installed!");
        }

        //Button ID
        const connectButton = document.getElementById("connect");

        //Click Event
        connectButton.addEventListener("click", () => {
            connectAccount();
        });

        //Connect Account Function
        async function connectAccount() {
            const accounts = await (window as any).ethereum.request({
                method: "eth_requestAccounts",
            });
            const account = accounts[0];
            connectButton.innerHTML =
                account[0] +
                account[1] +
                account[2] +
                account[3] +
                account[4] +
                account[5] +
                "..." +
                account[38] +
                account[39] +
                account[40] +
                account[41];
        }
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Connect MetaMask</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <button className={styles.connect} id="connect">
                Connect Wallet
            </button>
        </div>
    );
}